name: Sync LeetCode History

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

# CRITICAL: Permits the GitHub bot to write files into your repo
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run LeetCode Sync Action
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: 'LeetCode'
          verbose: true
          commit-header: '[LeetCode Sync] Solved'
